- $formkit: 'text'
  name: 'email'
  value: '$email'
  label: '邮件'
  help: '这个将被作为账户名称使用'
  validation: 'required|email'

- $formkit: 'password'
  name: 'password'
  value: '$password'
  label: '密码'
  help: '输入你的密码'
  validation: 'required|length:5,16'

- $formkit: 'password'
  name: 'password_confirm'
  value: '$password_confirm'
  label: '确认密码'
  help: '再输入一遍相同的确认密码'
  validation: 'required|confirm'
  validationLabel: '密码验证'
