- $formkit: 'text'
  name: 'apiBaseUrl'
  value: '$apiBaseUrl'
  label: '基础URL'
  help: '您alist的基础url,如https://domain:port'
  validation: 'required|url'

- $formkit: 'text'
  name: 'apiUsername'
  value: '$apiUsername'
  label: '用户名'
  help: '您alist的用户名。'
  validation: 'required|length:3,16'

- $formkit: 'password'
  name: 'apiPassword'
  value: '$apiPassword'
  label: '密码'
  help: '您alist的密码，用于申请Token访问令牌。'
  validation: 'required|length:5,36'

- $cmp: 'FormKit'
  props:
    name: 'enableAutoTokenRefresh'
    value: "$enableAutoTokenRefresh == 'true'"
    type: 'checkbox'
    id: 'enableAutoTokenRefresh'
    label: '当Token过期，是否自动刷新？'


- $formkit: 'text'
  name: 'apiToken'
  value: '$apiToken'
  type: 'hidden'

- $formkit: 'text'
  name: 'apiExpire'
  value: '$apiExpire'
  type: 'hidden'