# A unique name, must eq var console/vite.config.js#pluginEntryName,
# and can not contain specific symbol such as - .
name: PluginStarter
# plugin entry class that extends BasePlugin
clazz: run.ikaros.plugin.starter.StarterPlugin
# plugin 'version' is a valid semantic version string (see semver.org).
version: 0.11.0
requires: ">=0.11.4"
author:
  name: Ikaros OSS Team
  website: https://github.com/ikaros-dev
logo: https://ikaros.run/logo.png
homepage: https://github.com/ikaros-dev/plugin-starter
displayName: "插件快速开始模板"
description: "这是一个插件快速开始模板"
license: "AGPL-3.0"